name = "ant-colony-defense"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[env.production]
route = "ant-colony-defense.franzai.com/*"

[[kv_namespaces]]
binding = "GAME_STATE"
id = "ebc6c6ab80324920bfa913fd2c48c2b5"

[durable_objects]
bindings = [
  { name = "GAME_SESSION", class_name = "GameSession" }
]

[vars]
ENVIRONMENT = "production"